### PR TITLE
Add thanos sidecar to parca-analytics

### PR DESCRIPTION
**Pull request by metalmatze**
Additionally, added some docs on how to create the objectstorage secret for thanos, as this is always going to be manual.

### CODE REVIEW

**Comment by metalmatze** [comment]
I've run `argocd app diff scaleway-parca-demo-monitoring --revision=prometheus-analytics-thanos` and there's no meaningful output because I simply `kubectl edit` the existing deployment to retain Prometheus blocks already. 

Adding a PVC to prevent data loss when restarting Pods might make sense. However, I want to check if we can't use a graceful shutdown with  the Thanos sidecar to make sure it finishes uploading first.

**Review by brancz — APPROVED** [review]
lgtm but @maxbrunet should probably review as well

**Comment by metalmatze** [comment]
By default, the Prometheus runs with. I think this is fine until it ever becomes a problem. 
```yaml
    resources:
      limits:
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 512Mi
```

**Comment by metalmatze** [comment]
Alright, now we have an output. :tada: 

```diff

===== /Service parca-analytics/prometheus-parca-analytics ======
62a63,66
>   - name: grpc
>     port: 10901
>     protocol: TCP
>     targetPort: 10901

===== monitoring.coreos.com/Prometheus parca-analytics/parca-analytics ======
166a167,177
>   storage:
>     volumeClaimTemplate:
>       apiVersion: v1
>       kind: PersistentVolumeClaim
>       spec:
>         accessModes:
>         - ReadWriteOnce
>         resources:
>           requests:
>             storage: 5Gi
>         storageClassName: scw-bssd-retain

===== monitoring.coreos.com/PrometheusRule /prometheus-parca-analytics-thanos-sidecar-rules ======
0a1,43
> apiVersion: monitoring.coreos.com/v1
> kind: PrometheusRule
> metadata:
>   annotations:
>     argocd.argoproj.io/tracking-id: scaleway-parca-demo-monitoring:monitoring.coreos.com/PrometheusRule:parca-analytics/prometheus-parca-analytics-thanos-sidecar-rules
>   labels:
>     app.kubernetes.io/component: prometheus
>     app.kubernetes.io/instance: parca-analytics
>     app.kubernetes.io/name: prometheus
>     app.kubernetes.io/part-of: kube-prometheus
>     app.kubernetes.io/version: 2.47.2
>     prometheus: parca-analytics
>     role: alert-rules
>   name: prometheus-parca-analytics-thanos-sidecar-rules
> spec:
>   groups:
>   - name: thanos-sidecar
>     rules:
>     - alert: ThanosSidecarBucketOperationsFailed
>       annotations:
>         description: Thanos Sidecar {{$labels.instance}} in {{$labels.namespace}}
>           bucket operations are failing
>         runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/thanossidecarbucketoperationsfailed
>         summary: Thanos Sidecar bucket operations are failing
>       expr: |
>         sum by (namespace, job, instance) (rate(thanos_objstore_bucket_operation_failures_total{job="thanos-sidecar"}[5m])) > 0
>       for: 5m
>       labels:
>         severity: critical
>     - alert: ThanosSidecarNoConnectionToStartedPrometheus
>       annotations:
>         description: Thanos Sidecar {{$labels.instance}} in {{$labels.namespace}}
>           is unhealthy.
>         runbook_url: https://runbooks.prometheus-operator.dev/runbooks/prometheus/thanossidecarnoconnectiontostartedprometheus
>         summary: Thanos Sidecar cannot access Prometheus, even though Prometheus seems
>           healthy and has reloaded WAL.
>       expr: |
>         thanos_sidecar_prometheus_up{job="thanos-sidecar"} == 0
>         AND on (namespace, pod)
>         prometheus_tsdb_data_replay_duration_seconds != 0
>       for: 5m
>       labels:
>         severity: critical

===== /Service parca-analytics/prometheus-parca-analytics-thanos-sidecar ======
0a1,27
> apiVersion: v1
> kind: Service
> metadata:
>   annotations:
>     argocd.argoproj.io/tracking-id: scaleway-parca-demo-monitoring:/Service:parca-analytics/prometheus-parca-analytics-thanos-sidecar
>   labels:
>     app.kubernetes.io/component: thanos-sidecar
>     app.kubernetes.io/instance: parca-analytics
>     app.kubernetes.io/name: prometheus
>     app.kubernetes.io/part-of: kube-prometheus
>     app.kubernetes.io/version: 2.47.2
>   name: prometheus-parca-analytics-thanos-sidecar
>   namespace: parca-analytics
> spec:
>   clusterIP: None
>   ports:
>   - name: grpc
>     port: 10901
>     targetPort: 10901
>   - name: http
>     port: 10902
>     targetPort: 10902
>   selector:
>     app.kubernetes.io/component: prometheus
>     app.kubernetes.io/instance: parca-analytics
>     app.kubernetes.io/name: prometheus
>     app.kubernetes.io/part-of: kube-prometheus

===== monitoring.coreos.com/ServiceMonitor /thanos-sidecar ======
0a1,20
> apiVersion: monitoring.coreos.com/v1
> kind: ServiceMonitor
> metadata:
>   annotations:
>     argocd.argoproj.io/tracking-id: scaleway-parca-demo-monitoring:monitoring.coreos.com/ServiceMonitor:parca-analytics/thanos-sidecar
>   labels:
>     app.kubernetes.io/component: thanos-sidecar
>     app.kubernetes.io/instance: parca-analytics
>     app.kubernetes.io/name: prometheus
>     app.kubernetes.io/part-of: kube-prometheus
>     app.kubernetes.io/version: 2.47.2
>   name: thanos-sidecar
> spec:
>   endpoints:
>   - interval: 30s
>     port: http
>   jobLabel: app.kubernetes.io/component
>   selector:
>     matchLabels:
>       app.kubernetes.io/component: thanos-sidecar

===== tanka.dev/Environment /environments/scaleway-parca-demo ======
```

**Comment by metalmatze** [comment]
Given it's 1700 UTC and a block was just uploaded, plus the PR is green and I think this is in good shape now, I'll merge.
If there are any fixes we should follow up with, let me know.

**Comment by metalmatze** [comment]
The deployment worked flawlessly :partying_face:

**Pull request merged**
