### PR TITLE
fix(parca): configure NGINX ingress for GRPC

### PR DESCRIPTION
**Pull request by maxbrunet**
I was toying with this, it would allow to use the GRPC protocol to communicate with the demo:

```console
$ grpcurl demo.parca.dev:443 grpc.health.v1.Health/Check
{
  "status": "SERVING"
}
```

I saw this client failing with HTTP 415 (Unsupported Media Type), it's in Scaleway, but in another account I think (`parca-load` in Pyrra's account?):

```
51.15.51.214 - - [31/May/2023:19:55:34 +0000] "POST /parca.query.v1alpha1.QueryService/Query HTTP/2.0" 415 63 "-" "grpc-go-connect/1.1.0 (go1.18.10)" 98 0.001 [parca-parca-http] [] 100.64.2.183:7070 72 0.000 415 93c8ab7948a074a26b2435c8cb1808db
```

@metalmatze should it use GRPC-Web under `/api/` like the UI does? Or could we switch it to regular GRPC? 

<details>
<summary>diff</summary>

```diff
===== networking.k8s.io/Ingress parca/parca-grpc ======
diff --git a/tmp/argocd-diff2343086198/parca-grpc-live.yaml b/tmp/argocd-diff2343086198/parca-grpc
index e69de29..8c99a97 100644
--- a/tmp/argocd-diff2343086198/parca-grpc-live.yaml
+++ b/tmp/argocd-diff2343086198/parca-grpc
@@ -0,0 +1,72 @@
+apiVersion: networking.k8s.io/v1
+kind: Ingress
+metadata:
+  annotations:
+    argocd.argoproj.io/tracking-id: scaleway-parca-demo-parca:networking.k8s.io/Ingress:parca/parca-grpc
+    kubernetes.io/ingress.class: nginx
+    nginx.ingress.kubernetes.io/backend-protocol: GRPC
+  labels:
+    app.kubernetes.io/component: observability
+    app.kubernetes.io/instance: parca
+    app.kubernetes.io/name: parca
+    app.kubernetes.io/version: v0.17.0
+  name: parca-grpc
+  namespace: parca
+spec:
+  rules:
+  - host: demo.parca.dev
+    http:
+      paths:
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /grpc.health.v1.Health
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /grpc.reflection.v1alpha.ServerReflection
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /parca.debuginfo.v1alpha1.DebuginfoService
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /parca.profilestore.v1alpha1.AgentsService
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /parca.profilestore.v1alpha1.ProfileStoreService
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /parca.query.v1alpha1.QueryService
+        pathType: Prefix
+      - backend:
+          service:
+            name: parca
+            port:
+              name: http
+        path: /parca.scrape.v1alpha1.ScrapeService
+        pathType: Prefix
+  tls:
+  - hosts:
+    - demo.parca.dev
+    secretName: demo-parca-dev-tls
```

</details>

### CODE REVIEW

**Comment by maxbrunet** [comment]
@metalmatze Actually it would be nice to support both GRPC and GRPC-Web, but NGINX does not support that ([kubernetes/ingress-nginx6297 (comment)](https://github.com/kubernetes/ingress-nginx/issues/6297#issuecomment-705668888)).

I suggest we replace `ingress-nginx` by an Envoy-based ingress controller like [Contour](https://projectcontour.io/), it should have better support for GRPC: https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/other_protocols/grpc.html

What do you think?

**Comment by metalmatze** [comment]
parca-load actually uses connect-go to speak gRPC with Parca: 
https://github.com/parca-dev/parca-load/blob/c2c7a08ddb99c9ca40952895ef24907bd11e03b4/go.mod#L6

It would be indeed great to support gRPC, gRPC-web and connect-go I guess. If switching to something like Contour makes it easier, we can definitely try those. I know about them since forever but never actually used Envoy or Contour. Happy to try!

**Comment by maxbrunet** [comment]
> I know about them since forever but never actually used Envoy or Contour. Happy to try!

Same, I have been looking for a good excuse to try them

**Comment by maxbrunet** [comment]
So I tried Contour, but nothing under `/api` works, we are blocked by this issue :disappointed::

> Contour configures Envoy to automatically convert [gRPC-Web](https://github.com/grpc/grpc-web) HTTP/1 requests to gRPC over HTTP/2 RPC calls to an upstream service. This is a convenience addition to make usage of gRPC web application client libraries and the like easier.
> 
> Note that you still must provide configuration of the upstream protocol to have gRPC-Web requests converted to gRPC to the upstream app. If your upstream application does not in fact support gRPC, you may get a protocol error. In that case, please see [this issue](https://togithub.com/projectcontour/contour/issues/4290).

https://projectcontour.io/docs/1.25/guides/grpc/#grpc-web

A quick sum up of what works and what does not in each cases:

|             | Ingress-NGINX | Ingress-NGINX (this PR) | Contour          |
| ----------- | :-----------: | :---------------------: | :--------------: |
| gRPC on `/` | :negative_squared_cross_mark: (does not expect gRPC) | :heavy_check_mark: | :heavy_check_mark: |
| gRPC-Web on `/` | :heavy_check_mark: | :negative_squared_cross_mark: (expects gRPC) | :heavy_check_mark: (unnecessarily converted to gRPC) |
| gRPC-Web on `/api` | :heavy_check_mark: | :heavy_check_mark: | :negative_squared_cross_mark: (converted to gRPC) |

Envoy still seems like a good solution, but Contour does not configure it in a way that would work for us at the moment.

**Comment by maxbrunet** [comment]
I apologize for blaming these reserve proxies for an issue that was on our end :see_no_evil:, full gRPC and gRPC-Web support should be fixed once parca-dev/parca#3352 is released!

**Pull request merged**
